### PR TITLE
Italics

### PR DESCRIPTION
**Pull request by cssobral2013**
This PR includes Italics, its TTF binaries, and its source.

### CODE REVIEW

**Comment by alerque** [comment]
Can you please remove the built TTF files from this? Per the other‌ PR's in progress on this font everything is going to be autogenerated in CI jobs and posted as artifacts & attached to releases. The binary generated fonts won't be in the repository itself.

It will be a lot easier to review this PR if it only includes the relevant changes to the source.

**Comment by alerque** [comment]
P.S. If you're unsure how to rebase this branch to do that just comment and I'd be happy to do it, it's a pretty easy step with the right tools but definitely more advanced Git foo ;-)

**Review by alerque — CHANGES_REQUESTED** [review]
Please rebase to remove all the generated *.ttf files.

**Comment by cssobral2013** [comment]
@alerque - Completed!

**Comment by alerque** [comment]
Quoted form [parallel PR](https://github.com/theleagueof/league-spartan/pull/27#issuecomment-683637895):

> Thanks @cssobral2013. I'm in much the same boat being on Linux. I've tagged both your original PR and this on as `help wanted` and would encourage anybody who is interested in taking this on to drop a comment and I'd be glad to help work through the process. But we do need somebody with Glyphs and a working knowledge of it.
>
> Eventually Fontship should facilitate the process of contributing to fonts using any editor by providing  conversion between source formats, but that bit is under-developed right now.
>
> Additionally this PR *should* be building the Italic font as ready to use binary artifacts that anybody could test, but there is a syntax problem with the Glyphs file. Until that is worked out we can't even really preview how this would fit in.
>
> Again to **anybody interested in helping**, please drop a line here and I'll help you get rolling.

**Pull request closed without merging**
